DEBOUNCE_TYPE = asym_eager_defer_pk
TAP_DANCE_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes

# firmware size reduction
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
QMK_SETTINGS = no

COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no